### PR TITLE
Temporary fix Amazon Prime EU (+global?) - removal of api usage

### PR DESCRIPTION
**Pull request by ITSYV**
Added a service for Amazon Prime EU. Just using the same way the other services work.
Still needs fix for history sync, but not sure how we can solve this so both the EU and American version works

By the way, is there an option to add names to the "suggestion" list?
Shameless is called "Shameless: the complete series", but can't be found that way. I fixed it at this moment with splitting the title. But that's not best practice :)

### CODE REVIEW

**Comment by rafaelgomesxyz** [comment]
I don't like the idea of adding separate versions of a service for different regions. It should be just one for all. There's a way to make it work by taking advantage of the fact that it uses the next method as fallback when a method doesn't work. I can work on it when I have some time.

> By the way, is there an option to add names to the "suggestion" list?

Not entirely sure what you mean. You can't correct it by providing the URL to the correct item?

**Comment by ITSYV** [comment]
You're totally right. I just made a separate one for the ease of use at this moment. I wasn't sure what your idea is with the Prime API.
Just wanted to share :)

> Not entirely sure what you mean. You can't correct it by providing the URL to the correct item?
No, it just doesn't recognize the item if i remove the split function. So I can't provide a correct url :)

**Comment by MrMamen** [comment]
What is the status of this branch? Is it relevant?

**Comment by ITSYV** [comment]
Not really.
The code could be used to make a fallback for the non-api version, and the API version should be extended with regional API url's. But I lack the experience with typescript to do this myself

**Comment by rafaelgomesxyz** [comment]
Yeah, I'll work on this soon.

**Pull request closed without merging**
