### PR TITLE
Added Kijk.nl & Wakanim.Tv & Player.pl & HBO Go & Polsat Box streaming service

### PR DESCRIPTION
**Pull request by ITSYV**

### CODE REVIEW

**Review by MrMamen — DISMISSED** [review]

**Comment by bnowakow** [comment]
player.pl scrobling works

**Comment by ITSYV** [comment]
By the way, the `npx trakt-tools dev update-readme` command doesn't seem to work

**Comment by rafaelgomesxyz** [comment]
Hasn't HBO Go been replaced with HBO Max? Or is it still available in some regions?

**Comment by Jackenmen** [comment]
It's going to be available in Poland (and perhaps other EU countries?) on March 8th. For now, there's still only HBO GO here.

**Review by rafaelgomesxyz — APPROVED** [review]

**Comment by rafaelgomesxyz** [comment]
Got it.

@ITSYV Thanks for all the contributions!

**Pull request merged**
