### PR TITLE
Adding Belgian Streamz service

### PR DESCRIPTION
**Pull request by ITSYV**

### CODE REVIEW

**Comment by rafaelgomesxyz** [comment]
Are you able to rebase it so that only the last commit is in this PR?

**Comment by ITSYV** [comment]
> Are you able to rebase it so that only the last commit is in this PR?

Can you tell me how to do that? I did a rebase with sourcetree and pushed, but nothing seems to have happened

**Comment by rafaelgomesxyz** [comment]
First, you have to sync your master with ours. Get the new commits:

```
git remote add upstream https://github.com/trakt-tools/universal-trakt-sync.git
git fetch upstream
```

Now sync your master with ours:

```
git checkout master
git reset --hard upstream/master
git push --force
```

And finally rebase the commits starting from 6b3aa86 (which is just itself) on master:

```
git checkout Streamz
git rebase --onto master 6b3aa86^
git push --force
```

That should leave only the commit 6b3aa86 in this PR.

**Comment by rafaelgomesxyz** [comment]
> ```
> git checkout master
> git reset --hard upstream/master
> git push --force
> ```

By the way, the reset and forced push here are only necessary because you worked on master for the other PR, leaving your master ahead of ours. Usually, when you create separate branches for PRs and leave your master untouched, you can just push normally:

```
git checkout master
git pull upstream master
git push
```

This is one of the reasons why, when working on forks, it's better to leave master alone and create separate branches.

**Comment by ITSYV** [comment]
Thanks for the help and the info!
I just ran the commands, so should be fine now?

**Review by rafaelgomesxyz — APPROVED** [review]
Yep, thanks for the contribution again!

**Pull request merged**
