### PR TITLE
HBO Max bug fixes and enhancements

### LINKED ISSUE #133: HBO Max: History item url fails to load, breaking history sync
I'm getting "Failed to load history" when trying to sync HBO Max history. 

Status 500 when trying to request one of the endpoints for a movie, the response is:
`{"message":"An unknown problem occurred. Please contact your TV provider.","statusCode":500}`

I looked up what the URL looks like for when browsing the webpage normally, and it seems that what's breaking it is the missing of the following parameters:
```
&brand=HBO%20MAX&territory=NORDICS&navigation-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE&upsell-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE&playback-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE
```

Here's the URL that's failing (adding the above parameters makes it work): https://comet-emea.api.hbo.com/express-content/urn:hbo:feature:GX9KHPw1OIMPCJgEAAAAD?device-code=desktop&product-code=hboMax&api-version=v9.0&country-code=US&language=en-us

### PR DESCRIPTION
**Pull request by rafaelgomesxyz**
Bug fixes:

* Bug that does not retrieve metadata for items (fixes #133)
* Bug that does not detect that user is logged in
* Bug that does not scrobble/sync

For testing:

[chrome.zip](https://github.com/trakt-tools/universal-trakt-scrobbler/files/9691074/chrome.zip)
[firefox.zip](https://github.com/trakt-tools/universal-trakt-scrobbler/files/9691076/firefox.zip)

### CODE REVIEW

**Comment by smoothlystable** [comment]
I'm getting the following popup now:
```
Looks like you're not logged in to this service. Please go to the page below and log in before trying to sync.

https://www.hbomax.com/
```

The issue is that I'm always logged out from that webpage, I need to click Login and then it automatically signs me in. 
Is it possible to change the url/get the info needed from `https://play.hbomax.com/` instead? That's where I get forwarded to after clicking `Login` on `www.hbomax.com` and I'm always signed in when going directly to `https://play.hbomax.com/`.

**Comment by smoothlystable** [comment]
Just wanted to confirm that changing `HOST_URL` from `https://www.hbomax.com` to `https://play.hbomax.com` fixed the issue for me.

**Comment by MrMamen** [comment]
I changed several keys for retrieving storage as well as attributes on response data. Please make sure that this is valid for other regions. (I'm in Norway, Europe) If there indeed are several regional differences we need to expand the codebase for several scenarios.

**Comment by smoothlystable** [comment]
Confirming that login works great for Sweden, Europe.

It doesn't collect all items from my history for some reason (only getting two items), but that's another issue.

**Comment by rafaelgomesxyz** [comment]
Scrobbling is broken for me, I'll try to fix it.

**Comment by rafaelgomesxyz** [comment]
Can you guys confirm if the URL also changed for you guys from e.g. `https://play.hbomax.com/episode/urn:hbo:episode:XXXXXXXXXXXXXXXXXXXX` to `https://play.hbomax.com/player/urn:hbo:episode:XXXXXXXXXXXXXXXXXXXX` (notice the `player`). That's what's preventing the scrobble for me.

**Comment by smoothlystable** [comment]
Seems to be `player` for me as well, ex: `https://play.hbomax.com/player/urn:hbo:episode:GYsYeyA2EnHmangEAAAPc`

**Comment by rafaelgomesxyz** [comment]
There are new `.zip` files in the PR description with the latest changes. Please try those. Scrobble/sync is working 100% for me now.

**Comment by rafaelgomesxyz** [comment]
> It doesn't collect all items from my history for some reason (only getting two items), but that's another issue.

This might be because HBO Max doesn't have an actual history. If you go to your profile page (https://play.hbomax.com/profile) and check the `Continue Watching` tab, do you see more than 2 items there? Because that's where the extension grabs your "history" from (items are only kept there for a limited time, I think 30 days?).

**Comment by smoothlystable** [comment]
Scrobble and sync works for me now as well.

> This might be because HBO Max doesn't have an actual history. If you go to your profile page (https://play.hbomax.com/profile) and check the Continue Watching tab, do you see more than 2 items there? Because that's where the extension grabs your "history" from (items are only kept there for a limited time, I think 30 days?).

That makes sense, thanks for explaining. 
Looks like you can get history if you know the IDs, so I guess one way could be to do a content request with `{id: "urn:hbo:query:mylist"}` in the body, to get all the IDs from My List and then add them to the history check. That way you would probably catch a lot of items, since I think it's pretty common to add stuff to the list and watch them later (they don't get automatically cleared from list after being watched either). But it would also be nice if you wanna sync a specific item, just having to temporary add them to My List for the sync. 
But that's probably not really a priority, but maybe a thought for later.

**Comment by rafaelgomesxyz** [comment]
> Scrobble and sync works for me now as well.

Awesome, @MrMamen I think it's ready for merging.

> Looks like you can get history if you know the IDs, so I guess one way could be to do a content request with {id: "urn:hbo:query:mylist"} in the body, to get all the IDs from My List and then add them to the history check. That way you would probably catch a lot of items, since I think it's pretty common to add stuff to the list and watch them later (they don't get automatically cleared from list after being watched either). But it would also be nice if you wanna sync a specific item, just having to temporary add them to My List for the sync.
But that's probably not really a priority, but maybe a thought for later.

Yep, that's similar to how @schteff had implemented the Telia Play service (pretty sure they did exactly that, taking the items from "My List" and retrieving the history for them). So I might take some inspiration from their code and implement it like that for HBO Max.

I'll probably focus on that after the extension is released though, because right now my priority is updating it to Manifest v3, which will be a pain.

**Review by MrMamen — APPROVED** [review]

**Comment by MrMamen** [comment]
Where did my expanded instructions on the readme-file go?

**Comment by rafaelgomesxyz** [comment]
> Where did my expanded instructions on the readme-file go?

Oh, forgot to say, I think you should open a separate PR for that, as it's out of scope for these HBO Max changes.

**Pull request merged**
