### PR TITLE
Updates the name of cli from trakt-tools to @trakt-tools/cli

### PR DESCRIPTION
**Pull request by chaptergy**
Updates the README to contain the correct CLI package name

### CODE REVIEW

**Comment by rafaelgomesxyz** [comment]
Just `trakt-tools` should work, because of https://github.com/trakt-tools/cli/blob/main/package.json#L8. Did it not work for you?

**Comment by chaptergy** [comment]
> Just `trakt-tools` should work, because of https://github.com/trakt-tools/cli/blob/main/package.json#L8. Did it not work for you?

Using `trakt-tools` directly is only possible, if `@trakt-tools/cli` is already installed. Otherwise you get the following error:

```
> npx trakt-tools
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/trakt-tools - Not found
npm ERR! 404 
npm ERR! 404  'trakt-tools@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by rafaelgomesxyz** [comment]
That's the thing, it should always be installed if you installed the dependencies (which should be the first step after cloning the repo anyway), because it's listed in the dev dependencies.

It's a lot faster to type `npx trakt-tools` than `npx @trakt-tools/cli`, so that's why I'd prefer not to do this change if we don't need to.

**Comment by chaptergy** [comment]
You're right, I'm sorry. I forgot, that when I encountered the issue I reset my git folder right before, causing the node modules to be lost

**Pull request closed without merging**
