### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by ITSYV**

### CODE REVIEW

**Comment by ITSYV** [comment]
@rafaelgomesxyz 2 errors because it's the same in Dutch as in English. Should I remove "home" and "streamingServicesName" from the Dutch translations so it reverts to English or keep it and ignore these errors?

**Comment by rafaelgomesxyz** [comment]
I've made some changes to the translation linter that make this easier, so I went ahead and applied those changes here.

I'm gonna wait to merge this PR though, because I'm working on other PRs that will add new messages, so they will have to be translated as well.

**Comment by ITSYV** [comment]
@rafaelgomesxyz Can you change something in master: It seems that "hasScrobbler & hasSync:" changed values for "goplay-be". Scrobbler has to be true and sync false.
It seems stupid to make an extra PR for this :)

**Comment by rafaelgomesxyz** [comment]
> @rafaelgomesxyz Can you change something in master: It seems that "hasScrobbler & hasSync:" changed values for "goplay-be". Scrobbler has to be true and sync false.
> It seems stupid to make an extra PR for this :)

Yeah, I noticed that as well, I'll fix it when I merge #63.

**Comment by MrMamen** [comment]
> I'm gonna wait to merge this PR though, because I'm working on other PRs that will add new messages, so they will have to be translated as well.

Do you have more on the horizon? I think this should be merged soon.

**Comment by rafaelgomesxyz** [comment]
> Do you have more on the horizon? I think this should be merged soon.

I do. At least a couple PRs I'm working on will add new messages. I think it's best to wait for those.

**Review by rafaelgomesxyz — APPROVED** [review]
Finally merging, sorry it took so long. Some new messages have been added, if you wish to translate them you can go to https://crowdin.com/project/universal-trakt-scrobbler because we're using Crowdin now to manage translations.

**Comment by ITSYV** [comment]
> Finally merging, sorry it took so long. Some new messages have been added, if you wish to translate them you can go to https://crowdin.com/project/universal-trakt-scrobbler because we're using Crowdin now to manage translations.

No problem! I'll do the extra translations at Crowdin!
Any news on a final release by the way?

**Comment by rafaelgomesxyz** [comment]
Thanks for the translations!

> Any news on a final release by the way?

Not yet, still have a few things I want to do before the release.

**Pull request merged**
