### PR TITLE
Remove the broken Telia Play service

### PR DESCRIPTION
**Pull request by schteff**
Telia Play has had a new API since the summer. I personally don't use Telia Play anymore since they added HBO Max as a separate service.

### CODE REVIEW

**Comment by schteff** [comment]
Related issue: https://github.com/trakt-tools/universal-trakt-scrobbler/issues/64

**Review by rafaelgomesxyz — APPROVED** [review]

**Review by MrMamen — APPROVED** [review]

**Comment by MrMamen** [comment]
This change caused some errors in the extension on options:
`Uncaught Error: Service not registered for telia-play
    at getService (options.js:38341:11)`

**Comment by rafaelgomesxyz** [comment]
Yeah, had forgotten that it needs to be removed from the storage as well. Fix: #132

**Comment by schteff** [comment]
Sorry i missed that
Edit: I wouldn't have known how to update the storage anyway :)

**Pull request merged**
