### PR TITLE
Fix invalid dateformat in sync

### LINKED ISSUE #105: Sync history added with current date/time instead of watched date/time
This is probably because Trakt now uses UTC datetime instead of unix time stamp: https://trakt.docs.apiary.io/#reference/sync/add-to-history/add-items-to-watched-history

> Send a `watched_at` UTC datetime to mark items as watched in the past. This is useful for syncing past watches from a media center.

I did a quick test by sending the same request, but changed `watched_at` to UTC datetime format instead and it worked.

### PR DESCRIPTION
**Pull request by MrMamen**
Closes #105

### CODE REVIEW

**Comment by rafaelgomesxyz** [comment]
Is `date-fns-tz` actually needed? I thought this bug was just a format issue, because as far as I know the dates are already in UTC timezone.

**Comment by MrMamen** [comment]
I was not able to get the correct format in UTC without it. But I might have missed something in the API.

**Comment by rafaelgomesxyz** [comment]
Ok, will take a look soon.

**Comment by MrMamen** [comment]
When using `dateFns.formatISO` I always get the date in the local timezone. While the time is correct, the trakt API doesn't accept this. `date-fns-tz` was the only way I was able to get past this.

**Comment by rafaelgomesxyz** [comment]
But why use `dateFns.formatISO`? Couldn't you just get the UTC format by using the native `Date.toISOString`? So you could do `new Date(unix * 1e3).toISOString()` and get the desired format, no?

**Review by rafaelgomesxyz — APPROVED** [review]

**Pull request merged**
