### PR TITLE
Adding Disney Plus Service

### PR DESCRIPTION
**Pull request by ITSYV**

### CODE REVIEW

**Comment by rafaelgomesxyz** [comment]
The tests are still failing. You ran `npm run fix` and it gave no errors?

Also, you don't have to create a new PR every time. Just push to your branch and the commits will appear here.

**Comment by ITSYV** [comment]
> The tests are still failing. You ran `npm run fix` and it gave no errors?
> 
> Also, you don't have to create a new PR every time. Just push to your branch and the commits will appear here.

I only get errors on files I did not change

`scripts/generateRelease.js:45:5 - error TS2322: Type 'Buffer' is not assignable to type 'string'.

45     data: file.content,
       ~~~~

src/api/TraktAuth.ts:69:65 - error TS2345: Argument of type '(value: TraktAuthDetails | PromiseLike<TraktAuthDetails>) => void' is not assignable to parameter of type 'PromiseResolve<TraktAuthDetails>'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'TraktAuthDetails | PromiseLike<TraktAuthDetails> | undefined' is not assignable to type 'TraktAuthDetails | PromiseLike<TraktAuthDetails>'.
      Type 'undefined' is not assignable to type 'TraktAuthDetails | PromiseLike<TraktAuthDetails>'.

69    promise = new Promise((resolve) => void this.startManualAuth(resolve));
                                                                   ~~~~~~~

src/api/TraktAuth.ts:83:62 - error TS2345: Argument of type '(value: TraktAuthDetails | PromiseLike<TraktAuthDetails>) => void' is not assignable to parameter of type 'PromiseResolve<TraktAuthDetails>'.

83    return new Promise((resolve) => void this.startManualAuth(resolve));
                                                                ~~~~~~~

src/streaming-services/common/ScrobbleEvents.ts:37:11 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

37  abstract async checkForChanges(): Promise<void>;`

**Comment by ITSYV** [comment]
Code cleanup with the github errors checked :)
got no other errors with "npm run fix" except the 4 mentioned above

Only error I didn't fix was something with no await for an async method (parseProgress), but not sure how to fix that. It's a straight copy from the Netflix / Amazon files.

**Comment by rafaelgomesxyz** [comment]
Why did you add the file `src/streaming-services.ts`?

**Comment by ITSYV** [comment]
> Why did you add the file `src/streaming-services.ts`?

I got a message that 'disneyplus' should be disneyplus without the quotes, so I changed it.
And afterwards I noticed that I forgot to remove the streamz-be mention.

Building another service for streamz.be :)

**Comment by ITSYV** [comment]
> > Why did you add the file `src/streaming-services.ts`?
> 
> I got a message that 'disneyplus' should be disneyplus without the quotes, so I changed it.
> And afterwards I noticed that I forgot to remove the streamz-be mention.
> 
> Building another service for streamz.be :)

ooh, now I see what you mean. 
I uploaded it here on github. not on my dev pc right now

**Comment by rafaelgomesxyz** [comment]
I think most of the errors are because you're probably not running Prettier? Prettier should format all files automatically when you run `npm run fix`. Not sure why that's not happening for you.

**Comment by rafaelgomesxyz** [comment]
For the `parseItem` error, you just have to remove `async` from the function if it doesn't have `await`.

**Comment by ITSYV** [comment]
> I think most of the errors are because you're probably not running Prettier? Prettier should format all files automatically when you run `npm run fix`. Not sure why that's not happening for you.

reinstalled prettier, but still don't get other errors locally. Only the 4 above

There is no "async" on the parseProgress function..

**Comment by rafaelgomesxyz** [comment]
> > I think most of the errors are because you're probably not running Prettier? Prettier should format all files automatically when you run `npm run fix`. Not sure why that's not happening for you.
> 
> reinstalled prettier, but still don't get other errors locally. Only the 4 above
> 
> There is no "async" on the parseProgress function..

I think it's in `parseItem`.

**Comment by ITSYV** [comment]
Oh yep!
But isn't it supposed to be there? Also copied that from the other files.
I really have no clue about how that works :) I was already happy that it was working as expected 😄

**Comment by rafaelgomesxyz** [comment]
> Oh yep!
> But isn't it supposed to be there? Also copied that from the other files.
> I really have no clue about how that works :) I was already happy that it was working as expected 😄

It's probably because in the other files `await` is used somewhere in the function, and you didn't need to use it.

If `await` isn't used in the function, then `async` shouldn't be there. `async` is only required in asynchronous functions.

**Comment by ITSYV** [comment]
It seems that if I remove it, I get another error because it's not assignable to the same property in ScrobbleParser.

**Comment by rafaelgomesxyz** [comment]
> It seems that if I remove it, I get another error because it's not assignable to the same property in ScrobbleParser.

I see. Can you try changing the line https://github.com/trakt-tools/universal-trakt-scrobbler/blob/master/src/streaming-services/common/ScrobbleController.ts#L12 to `parseItem(): Promise<Item | undefined> | Item | undefined;`? That should make it assignable.

**Comment by ITSYV** [comment]
Done, next errors:
- TS2322: Type 'undefined' is not assignable to type 'Promise '.
- TS2739: Type 'Item' is missing the following properties from type 'Promise ': then, catch, [Symbol.toStringTag], finally

**Comment by ITSYV** [comment]
Or should I change the parseItem function to: "parseItem = (): Item | undefined => {" in my parser file?

**Comment by rafaelgomesxyz** [comment]
> Or should I change the parseItem function to: "parseItem = (): Item | undefined => {" in my parser file?

Yep, forgot to mention that.

**Comment by rafaelgomesxyz** [comment]
Also forgot to mention that you need to remove `await` from `const item = await DisneyplusParser.parseItem();`, since it's no longer async.

Sorry for the hassle with the errors! This hasn't been a problem before.

**Comment by ITSYV** [comment]
Updated!
No problem, if I knew more of Typescript, I probably would have noticed all these kinds of things. But never too old to learn I guess. 

If the Disney Plus addon is fully working and without errors, I'll give it a copy to add Streamz and some more Belgian streaming sites

**Comment by rafaelgomesxyz** [comment]
Looks good! Thanks for contributing!

**Review by rafaelgomesxyz — APPROVED** [review]

**Comment by rafaelgomesxyz** [comment]
Also, not sure if you're aware, but creating a separate branch to work on your PRs is better than working directly on master.

**Comment by ITSYV** [comment]
I am now! But I was already making a branch for Streamz. Noticed that it would indeed be more convenient that way.

**Pull request merged**
